name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name if different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build and deploy Static Web App
      - name: Build and deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"
          api_location: "api" # Set to 'api' or '.' if no backend
          output_location: "build"
          deployment_action: "upload" # This explicitly specifies the action
